### ISSUE TITLE
Unable to update notification

### ISSUE THREAD

**Issue by janousek** [thudugala/Plugin.LocalNotification#152]
**Describe the bug**
It is not currently possible to update the notification. Each time "NotificationCenter.Current.Show" is called, the old notification is cancelled: https://github.com/thudugala/Plugin.LocalNotification/blob/e7cfe52cdba93cb84d59cab092d854ca3cb7ef22/Source/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs#L145
This is problem if you want just update notification (progress, text, etc.). Currently there is a cancellation and a new notification, which is a problem if you need to update notification kždou second.

**To Reproduce**
Try to create new notification and each 1 second update the title and call NotificationCenter.Current.Show to show it.

**Expected behavior**
Title of the notification should update without createion of new notification.

**Proposed solution**
Add new method on NotificationCenter called "Update". This method will not call cancellation. Or add new options for method "Show" to don´t cancell existng notification.

**Comment by ArunPrakashG** [comment]
Isn't this fixed in the latest source ? 

[Check here](https://github.com/thudugala/Plugin.LocalNotification/blob/2284cd8b122985535afe03496534907553b26997/Source/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs#L163)

`cancelBeforeShow` bool controls it.
Setting it to false will not call the `Cancel()` on the notification.

**Comment by thudugala** [comment]
@ArunPrakashG the option is not exposed to top level. Will fix it soon.

**Comment by thudugala** [comment]
Fixed in version 6.0.0
