### ISSUE TITLE
No notifications in Android with long delay of NotifyTime

### ISSUE THREAD

**Issue by khaledbakeer** [thudugala/Plugin.LocalNotification#168]
**Describe the bug**
I created a Notification with NotifyTime 10 min and it worked on iOS and Android, until I changed the NotifyTime to +24 hours or greater, it worked on iOS but on Android I did not get any notifications

**Platform:**
 - Android: Tested on android 9, 10, 11 Not worked.
 - iOS Tested on 14.6 and worked perfectly.

**Smartphone:**
 - Device: [Samsung S8, S9, S20, iPhone 12]

**Comment by thudugala** [comment]
@khaledbakeer just tried myself in One Plus 7T and it worked for me. Can you try using different brands?

**Comment by deniskg89** [comment]
maybe the problem can be when user kills the app? (thats my case with new version of plugin. for old one v2.0.7 i do not have this problem)

**Comment by McFlemchSoda** [comment]
I'm having this issue as well, and I suspect it also has something to do with killing the app. It's a combination of a longer delay and killing the app in my case. Because when I schedule it for like 10 seconds and then kill the app, I still get the notification, but when I put it on something like 5 minutes, I don't receive any notification. Note I'm still using version 5.2. Was planning on upgrading until I also saw ticket #184 on the newest version. To be fair we've been having an issue with android long term notifications for a while. Our application needs to send one local notification once a month, but a lot of android users are not getting this notification. We schedule these notifications way ahead of time.

**Comment by thudugala** [comment]
@khaledbakeer and @McFlemchSoda Can you try version 9.0.0-preview01

**Comment by gaurakshay** [comment]
FWIW, I have tested version `9.0.0-preview01` for some time now. Here are my findings:

Device -> Pixel 3 XL (Physical Device)

I setup notifications to go off at different time intervals:
- 1 min
- 5 mins
- 30 mins
- 60 mins
- 5 hrs
- 24 hrs (1 day)
- 48 hrs (2 days)
- 72 hrs (3 days)
- 96 hrs (4 days)
- 120 hrs (5 days)

_Note:_ I didn't setup repeating alarms, just individual alams. I didn't kill the app, just pressed home button. Didn't reboot the phone. Every time a notification was delivered, I tapped on it as well.

All the notifications came through just fine. They might've been off by a minute or two but they all were delivered. I am pretty stoked about this preview :). Thanks @thudugala !!!

It is interesting that you've had to resort to `AlarmManager` instead of `WorkManager` as I thought that is what `Google` has been trying to push for some time now. But it doesn't work as good as `AlarmManager` I guess.

**Comment by thudugala** [comment]
@gaurakshay thank you for the test results.

**Comment by thudugala** [comment]
@gaurakshay after updating to preview04, did you uninstall the preview01 app from the device before deploying preview04?

**Comment by gaurakshay** [comment]
@thudugala Samsung S20 FE was a new device. Don't remember if I uninstalled the app from Google Pixel 3 XL.

**Comment by thudugala** [comment]
@gaurakshay I was able get notification popup, after updating to preview04

![image](https://user-images.githubusercontent.com/4112014/132149233-1f2a0d18-bd11-4fb5-a13d-33aa6909b245.png)

**Comment by gaurakshay** [comment]
I'll give it a try.

**Comment by thudugala** [comment]
released version 9.0.0
