### ISSUE TITLE
Notifications not appearing on Android if the app is closed/terminated

### ISSUE THREAD

**Issue by trystanwilcock** [thudugala/Plugin.LocalNotification#184]
Please forgive me if it wasn't a feature in the first place, but when I schedule a notification and terminate the app (swipe the app away), the notification won't appear until the app is opened again. If the app is still active in the background, it will appear fine. Is there a way in which notifications will show even if the app is closed?

Package version v8.0.1

**Reproduce**
Schedule a notification
Swipe away the app

**What should happen**
Notification should appear at time scheduled

**What actually happens**
Notification only appears once the application is opened 

**Platform(s)**
Google Pixel 2 (emulated) - Android 9.0
Samsung Galaxy S10 (plugged in to PC) - Android 10.0

**Code**
I am scheduling the notification(s) in a ContentPage as follows...

```
var nextDay = DateTimeFunctions.GetNextWeekday(dayOfWeek);

var notification = new NotificationRequest
{
        NotificationId = notificationId,
        Title = "Reminder!",
        Description = "It's time to take your blood pressure.",
        Schedule = new NotificationRequestSchedule
        {
                NotifyTime = new DateTime(nextDay.Year, nextDay.Month, nextDay.Day, reminder.Time.Hours, reminder.Time.Minutes, reminder.Time.Seconds),
                RepeatType = NotificationRepeat.Weekly,
        }
};

NotificationCenter.Current.Show(notification);
```

I have created the notification channel in the Android project in MainActivity.cs like so...

```
NotificationCenter.CreateNotificationChannel(new Plugin.LocalNotification.Platform.Droid.NotificationChannelRequest
{
        Name = "Urgent",
        Importance = NotificationImportance.High,
        EnableVibration = true,
        LockScreenVisibility = NotificationVisibility.Public
});
```

**Comment by McFlemchSoda** [comment]
Might also be related to #168 and vice versa. I'm having this issue as well when scheduling it for about 5 minutes later. Strange thing is, it does work for me if I schedule one 10 seconds later and quickly kill the app, then it still appears. But once I change it to 5 minutes later and kill the app, nothing appears.

**Comment by thudugala** [comment]
@trystanwilcock can you try  version v8.0.2

**Comment by McFlemchSoda** [comment]
I also just upgraded to v8.0.2 in my sample project, but still have the same results.
I scheduled a few notifications with a 5 minute interval. For the first two I killed the app after scheduling and waited for the two notifications to come. Nothing appears. I then opened the app and waited for the next 5 minute interval with the app running in the background. This notification did appear at the right time. 

Tested this on Samsung a50 and Huawei p30 devices, in a sample project.

**Comment by trystanwilcock** [comment]
I have upgraded to v8.0.2. To eliminate any possibility of the emulator not functioning correctly or attaching the debugger causing issues, I have been restarting my devices emulated Pixel 2 and Samsung S10 physical device) after build. 

To test, I have been scheduling notifications between 5 and 15 minutes into the future. For the most part, notifications seem to appear at the right time. There have been a few occasions where they would be a minute late. I will continue to test with longer wait periods for the notifications.

**Comment by thudugala** [comment]
@trystanwilcock and @McFlemchSoda Can you try version 9.0.0-preview01

**Comment by McFlemchSoda** [comment]
@thudugala Hiya, I've upgraded to 9.0.0-preview01 and repeated the same tests, interval of 5 minutes on Samsung a50 and Huawei p30 devices. Here are my outcomes. 

It does seem to work better than the 8.xx version. On the Samsung A50 I am getting the notifications every 5 minutes, whether the app in backgrounded or killed, so that's great! The only issue is that on my Huawei P30 I'm not getting all the notifications. The behaviour on the Huawei P30 is as follows:

I start the app which then schedules notifications with an interval of 5 minutes for about an hour. If the app is in the background I will get all notifications on the specified time. When I kill the app I DO get the first notification of the 5 minute interval after killing the app, so that's progress, but that's it. After that, I get none of the other notifications that are scheduled with the app killed. When I open de app a while after the fact, I immediately get ALL the missed notifications, so I had like 5 at once. 

I've been doing some testing in another project where I have the native android implementation, and with the same devices. With the native implementation I have been getting more notifications on the Huawei P30 while the app is killed. 
I'll keep testing in both projects, and will now also schedule some notification for tomorrow to see how it responds with longer delays.

**Comment by mos379** [comment]
@McFlemchSoda did you disable the battery management for your app on the huawei? 
I was having always issues with that until I changed the default setting.

**Comment by McFlemchSoda** [comment]
@thudugala Looking at my battery options, everything is turned off. No power saving modes on.

**Comment by thudugala** [comment]
@McFlemchSoda can you please attach the android native sample project here?

**Comment by McFlemchSoda** [comment]
@thudugala The native project is actually my own project, but since I just used the code from the Xamarin samples I guess I could make it a sample project as well. When I have some time I'll make a sample project, and will test that sample project again as well. To be continued.

**Comment by trystanwilcock** [comment]
Further testing on my Samsung s10 using the latest preview: I scheduled a notification around the same time as my alarm in the morning. Swiped the application away long before bed and it appeared on time as scheduled. Will continue to test. Thanks for your efforts @thudugala and @McFlemchSoda

**Comment by azrinsani** [comment]
Hi, this is still not working. I have tried even a fast 10 seconds later scheduled notification, which I close the app after 3 seconds. The Notifications never come up

**Comment by McFlemchSoda** [comment]
@thudugala Hey, sorry, I haven't had time to make the native android project or test the new preview. Hope you found some time to use the Xamarin Samples of native android local notifications to see differences. We now use the native implementation for local notifications because we had to fix these issues a bit faster. We also only use it to schedule them, nothing fancy with removing them or repeating them.

**Comment by thudugala** [comment]
Version 9 released, if you have preview version app installed. Then please uninstall it first.

**Comment by archergod** [comment]
Notification has stop working for me since I update to Version 9.

**Comment by MadSkilzGP** [comment]
Agreed. 
For me the only one that has worked is version 9.0.0-preview02 … prev 1, 3, 4 and now ver 9 doesn’t.

**Comment by GaborTheHutt** [comment]
On V9.x it still doesnt work for me, on 8.2 it triggers with 1 min delay.

**Comment by mrnams** [comment]
doesnt work in .net 8.0
