### ISSUE TITLE
Always display last Notification info whenever Tap on anyone of multi notification in android

### ISSUE THREAD

**Issue by vxvendetta001** [thudugala/Plugin.LocalNotification#312]
When there are more than one notification, pressing one always displays the information of the last one.
I downloaded the sources and fixed this problem by setting a random "requestCode" when calling "GetActivity" in the "CreateActionIntent" method

**Comment by thudugala** [comment]
@ vxvendetta001 Can you show your change using a Pull Request?

**Comment by thudugala** [comment]
@ vxvendetta001, can you provide the step-by-step guide to recreate the issue?

**Comment by vxvendetta001** [comment]
Steps to reproduce the behavior:

1) Open the sample app and (triple the  "send local notification" button OR click three times)  and change the notificationId and Title;

2) On the notification bar, are correctly displayed 3 notifications;

3) By clicking on the second or third notification, we will always display the information of the first

Platform:
Android (api 31)
Device: android emulator ; pixel 5

**Comment by vxvendetta001** [comment]
The proposed solution is just an example, i've read that the "requestCode" in "getActivity" call, must be unique

**Comment by thudugala** [comment]
@vxvendetta001 is the notification id the same for all 3 notifications?

Have you tried setting the notification id to be unique?

**Comment by vxvendetta001** [comment]
@thudugala The notification id is not the same, it is unique

**Comment by thudugala** [comment]
@vxvendetta001, will you be able to attach a sample project code here?

**Comment by vxvendetta001** [comment]
[Direct Maui.zip](https://github.com/thudugala/Plugin.LocalNotification/files/9960410/Direct.Maui.zip)

The problem's resolution is included in the project.

**Comment by TheMalle** [comment]
I think this is the same root cause for an issue I am having, where only the actions on the latest notification are usable. 

When setting up the `NotificationAction`s for the `NotificationCategory` they are given an `ActionId`. This ends up being used in the end by `NotificationServicesImpl.CreateActionIntent` as the `requestCode` for the `PendingIntent` created by `PendingIntent.GetActivity` or `PendingIntent.GetBroadcast`. This means that the same `requestCode` is used for actions on every notification from a given category, but the `requestCode` must be unique within (if I understand it correctly) the context and intent also provided to `GetActivity` and `GetBroadcast` to actually create a new `PendingIntent`. Since they are now all the same when a new notification is sent in a category, the actions on any previous notifications in the same category become disabled.

I replicated it using `Plugin.LocalNotification/Sample/Direct Maui/LocalNotification.Sample.sln` and setting a new `NotificationId` for each notification sent from the main page.

First notification sent.
![image](https://user-images.githubusercontent.com/22431531/206898769-aa75c2ed-7f2f-46f8-a2b7-6c6e829180ea.png)

Second notification sent with new `NotificationId`. Note the disabled actions on the second notification.
![image](https://user-images.githubusercontent.com/22431531/206898790-719faf1c-3d1d-4659-901b-8491d75c3b19.png)

Using random `requestCode`s to make them unique resolves it (as long as the randomly generated `int`s do not collide).
![image](https://user-images.githubusercontent.com/22431531/206900252-7f6cb370-a094-4481-abaf-1434eda2f518.png)

**Comment by thudugala** [comment]
Please try using version 10.1.1

**Comment by samuelwine** [comment]
@thudugala thanks for looking at this.
I spent quite some time trying to build 10.1.1. After having made a number of changes, I managed to get it to build, but the original issue appears to still be a problem.  Its possible I may not have built it correctly.
Is there any chance you could make a built dll accessible to me, so that I can test it properly?
