### ISSUE TITLE
[Android] Scheduled Local Notifications are not shown on time

### ISSUE THREAD

**Issue by JanNepras** [thudugala/Plugin.LocalNotification#37]
**Describe the bug**
I have a solution implementing scheduled local notifications. On Android notifications are sometimes delayed (0 - 40 seconds). What we need in our project to schedule local notification on specified time interval. 

I created solution replicating this issue. This project schedules 2 notifications. The first one is scheduled after 60 seconds and second one 120. 

**To Reproduce**
1. Download and run LocalNotificationTestingFinal
2. Click on the button bellow
3. Observe countdown and how notifications are sometimes delayed

**Expected behavior**
Notifications should be triggered exactly on specified second time interval.

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: Sasmung S8 
 - OS: Android 9
 - Version: API 28

**Additional context**
[LocalNotificationTestingFinal.zip](https://github.com/thudugala/Plugin.LocalNotification/files/3541242/LocalNotificationTestingFinal.zip)

**Comment by thudugala** [comment]
Please note that the delay is not always accurate. Due to how modern Android works.

**Comment by JanNepras** [comment]
@thudugala Could you please be more specific?

**Comment by thudugala** [comment]
Android Notification does not support trigger using time. Therefor I use WorkManager in Android to do a one time work with an initial delay. WorkManager, initial delay is not always accurate. 

This seems to be by design.

https://issuetracker.google.com/issues/110745313
https://medium.com/android-ideas/scheduling-notifications-on-android-with-workmanager-6d84b7f64613
https://stackoverflow.com/questions/53097297/work-manager-not-scheduling-work-with-setinitialdelay

**Comment by JanNepras** [comment]
@thudugala In that case we can close this bug.
