### ISSUE TITLE
Scheduled Notifications not working 

### ISSUE THREAD

**Issue by NiklasGameDev** [thudugala/Plugin.LocalNotification#79]
I'm trying to schedule a bunch of events for the whole day repeating everyday in Xamarin Forms. I have an array with events containing a timespan for the time of day and a name for the event. For testing purposes I'm scheduling these events in the constructor of my Testpage. I loop through all events and set the notification ID to the iteration index. I have a Testbutton to show a notification in 5 sec with a unique ID to test if notifications still work because I cant wait 30 minutes for the next event everytime. The problem is sometimes they show up sometimes they dont and when I open the app again they come all at once and at some point even the button notification in 5 sec doesnt work and I dont know why ?! 
I'm testing on Android btw.

**Comment by thudugala** [comment]
The OS decides when to show notifications. also on some devices, if the app is not in memory the notifications will not show up.

**Comment by zhijianglee** [comment]
Hi, First of all this doesn't work 
  
NotificationCenter.CreateNotificationChannel();
I am getting Notification Center doesn't contain a definition of  CreateNotificationChannel. Are you sure about this?

**Comment by thudugala** [comment]
@zhijianglee Please follow readme.md

**Comment by askinadze** [comment]
NotificationCenter.Current.Show(notification); 

It works only if NotifyTime is null

**Comment by Balu2** [comment]
Hi, I have the same error what zhijianglee has. I followed the readme: target android version is 10.0, When I install version 5.0.3 NotificationCenter doesn't have CreateNotificationChannel definition. When I go back to version 4.1.4 everything is ok again.

**Comment by Balu2** [comment]
But wait, I found the solution to this problem: You need to install the package Xamarin.AndroidX.Work.Runtime (v. 2.3.4.1) and Xamarin.AndroidX.MediaRouter (v1.1.0)

**Comment by thudugala** [comment]
Please try sample code https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet

**Comment by Balu2** [comment]
@thudugala, yes I tried this sample and compared it with my project settings. And so I discovered the solution as described above.

**Comment by thudugala** [comment]
@Balu2 Can you attach a sample solution ? So I can investigate as to why Xamarin.AndroidX.Work.Runtime (v. 2.3.4.1) and Xamarin.AndroidX.MediaRouter (v1.1.0) need to be referenced.

**Comment by Balu2** [comment]
@thudugala, it is a project of a customer so I am not able to distribute it. 
The project was defined in 2018 and the used packages were upgraded over time.  After upgrading your plugin to the latest version and settings target framework to Android 10, it resulted in the error I mentioned above.
On the other hand your sample project gave no errors, when I compiled it. So what I did this morning, was creating a new xamarin sample project, installed your plugin, defined target framework to Android 10 and made the neccessary changes in mainactivity.cs. Result: no problems anymore.
So probably the errors occured, because of the old project (defined in 2018 and upgraded overtime)
